AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWSLambda with Java 25 Spring Boot 4.0 AWS Serverless Java Container and Aurora DSQL
  Sample SAM Template 

Parameters:
  Stage:
    Type: String
    Default: prod
    
Globals:
  Function:
    CodeUri: target/aws-lambda-java-25-spring-boot-4.0-aws-serverless-java-container-aurora-dsql-1.0.0-SNAPSHOT.jar
    Runtime: java25
    Timeout: 30 
    MemorySize: 1024
    SnapStart:
      ApplyOn: PublishedVersions       
    Environment:
      Variables:
        #MAIN_CLASS: software.amazonaws.Application
        JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
        AURORA_DSQL_CLUSTER_ENDPOINT: !Sub ${DSQL}.dsql.${AWS::Region}.on.aws

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    DependsOn: MyApiCWLRoleArn 
    Properties:
      StageName: !Ref Stage
      Name: AWSLambdaSpringBoot40AWSServerlessJavaContainerDSQLAPI
      Description: Product API using AWS Lambda Java 25 Spring Boot 4.0 AWS Serverless Java Container and Aurora DSQL
      AccessLogSetting:
        DestinationArn: !Sub ${MyApiLogGroup.Arn} # This Log Group is already created within our SAM Template
        Format: "{'integrationLatency':'$context.integrationLatency', 'latency':'$context.responseLatency', 'requestId':'$context.requestId', 'ip': '$context.identity.sourceIp', 'caller':'$context.identity.caller', 'user':'$context.identity.user','requestTime':'$context.requestTime', 'xrayTraceId':'$context.xrayTraceId', 'wafResponseCode':'$context.wafResponseCode', 'httpMethod':'$context.httpMethod','resourcePath':'$context.resourcePath', 'status':'$context.status','protocol':'$context.protocol', 'responseLength':'$context.responseLength' }"
      #MethodSettings:
       # - MetricsEnabled: True
       #   ResourcePath: '/*'
       #   HttpMethod: '*'
      Auth:
        ApiKeyRequired: true  # sets for all methods


  MyApiCWLRoleArn:
   Type: AWS::ApiGateway::Account
   Properties: 
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn
      
  # IAM Role for API GW + CWL
  CloudWatchRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Path: /
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'         
        
  MyApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
       LogGroupName: !Sub "/aws/apigateway/${MyApi}"
       RetentionInDays: 7


  MyApiUsagePlan:
     Type: AWS::ApiGateway::UsagePlan
     DependsOn:  
        - MyApiStage
     Properties:
      ApiStages: 
        - ApiId: !Ref MyApi
          Stage: !Ref Stage
      UsagePlanName: AWSLambdaJava25SpringBoot40AWSSJCDSQLAPIUsagePlan
      Description: Usage plan for AWSLambdaJava25SpringBoot40AWSSJCDSQLAPI
      Quota:
          Limit: 2000000
          Period: DAY
      Throttle:
          RateLimit:  10000
          BurstLimit: 50000   

  MyApiKey: 
    Type: AWS::ApiGateway::ApiKey
    DependsOn:  
       - MyApiStage
    Properties: 
      Name: "AWSLambdaJava25SpringBoot40AWSSJCDSQLApiKey"
      Description: "AWSLambdaJava25SpringBoot40AWSSJCDSQL API Key"
      Enabled: true
      GenerateDistinctId: false
      Value: a6ZbcDefQW12BN56WEI40DS
      StageKeys:
        - RestApiId: !Ref MyApi
          StageName: !Ref Stage

  MyApiUsagePlanKey:
      Type: "AWS::ApiGateway::UsagePlanKey"
      DependsOn: 
      - MyApi
      Properties:
        KeyId: !Ref MyApiKey
        KeyType: API_KEY
        UsagePlanId: !Ref MyApiUsagePlan

  PostProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazonaws.example.product.handler.StreamLambdaHandler::handleRequest
      FunctionName: PostProductWithJava25SpringBoot40AWSSJCDSQL
      AutoPublishAlias: liveVersion
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dsql:DbConnectAdmin
              Resource: 
                 - !Sub arn:${AWS::Partition}:dsql:${AWS::Region}:${AWS::AccountId}:cluster/${DSQL}

      Events:
        PutRequest:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /products
            Method: post

  PostProductFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PostProductFunction}"
      RetentionInDays: 7

 
  GetProductByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazonaws.example.product.handler.StreamLambdaHandler::handleRequest
      FunctionName: GetProductByIdWithJava25SpringBoot40AWSSJCDSQL
      AutoPublishAlias: liveVersion
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dsql:DbConnectAdmin
              Resource: 
                 - !Sub arn:${AWS::Partition}:dsql:${AWS::Region}:${AWS::AccountId}:cluster/${DSQL}

      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /products/{id}
            Method: get            
            

  GetProductByIdFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetProductByIdFunction}"
      RetentionInDays: 7



  GetProductByIdWithFullPrimingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazonaws.example.product.handler.StreamLambdaHandlerWithFullPriming::handleRequest
      FunctionName: GetProductByIdWithJava25SpringBoot40AWSSJCDSQLAndFullPriming
      AutoPublishAlias: liveVersion
      Policies:
          Statement:
            - Effect: Allow
              Action:
                - dsql:DbConnectAdmin
              Resource: 
                 - !Sub arn:${AWS::Partition}:dsql:${AWS::Region}:${AWS::AccountId}:cluster/${DSQL}
      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /productsWithFullPriming/{id}
            Method: get            
            

  GetProductByIdFunctiondWithFullPrimingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetProductByIdWithFullPrimingFunction}"
      RetentionInDays: 7

 
  DSQL:
    Type: AWS::DSQL::Cluster
    Properties:
      DeletionProtectionEnabled: true 
      

Outputs:
  AWSLambdaJava25SpringBoot40AWSSJCDSQLAPIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for AWS Lambda with Java 25 Spring Boot 4.0 AWS Serverless Java Container and Aurora DSQL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/products"
